# Schema for the configuration files of the Custom form module.
custom_form.settings:
  type: config_object
  label: 'Custom form settings'
  mapping:
    example:
      type: string
      label: 'Example'
