<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Callback action on submit (custom method plus bas)
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function sign_in_form_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id == 'user_login_form') {

    // Code to modify your form input
    // $form['actions']['submit']['#submit'][] = 'custom_submit_method';.
    $form['fullName'] = [
      '#type' => 'textfield',
      '#title' => t('Full Name'),
      '#required' => TRUE,
    ];

  }
}
